2014/09/09 05:18:22 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\hs\protected\views\layouts\main.php:8)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#2 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(206): CContentDecorator->run()
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(300): SiteController->endWidget()
#5 C:\xampp\htdocs\hs\protected\views\layouts\column1.php(6): SiteController->endContent()
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): SiteController->renderInternal()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(784): SiteController->renderFile()
#9 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(32): SiteController->render()
#10 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#15 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\hs\index.php(13): CWebApplication->run()
REQUEST_URI=/hs/index.php?r=site/index
in C:\xampp\htdocs\hs\protected\views\layouts\main.php (8)
in C:\xampp\htdocs\hs\protected\views\layouts\column1.php (6)
in C:\xampp\htdocs\hs\protected\controllers\SiteController.php (32)
2014/09/18 00:49:57 [error] [exception.CException] exception 'CException' with message 'Property "State.city" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('city')
#1 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(34): CActiveRecord->__get('city')
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/hs/
---
2014/09/18 00:50:04 [error] [exception.CException] exception 'CException' with message 'Property "State.city" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('city')
#1 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(34): CActiveRecord->__get('city')
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/hs/
---
2014/09/18 00:50:11 [error] [exception.CException] exception 'CException' with message 'Property "State.City" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('City')
#1 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(34): CActiveRecord->__get('City')
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/hs/
---
2014/09/18 00:50:18 [error] [exception.CException] exception 'CException' with message 'Property "State.City" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('City')
#1 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(34): CActiveRecord->__get('City')
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/hs/
---
2014/09/18 00:50:44 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\hs\protected\controllers\SiteController.php:34)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\hs\index.php(13): CWebApplication->run()
REQUEST_URI=/hs/
in C:\xampp\htdocs\hs\protected\controllers\SiteController.php (34)
in C:\xampp\htdocs\hs\index.php (13)
2014/09/18 00:50:49 [error] [exception.CException] exception 'CException' with message 'Property "State.City" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('City')
#1 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(34): CActiveRecord->__get('City')
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/hs/
---
2014/09/18 00:55:01 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\hs\protected\controllers\SiteController.php:34)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\hs\index.php(13): CWebApplication->run()
REQUEST_URI=/hs/
in C:\xampp\htdocs\hs\protected\controllers\SiteController.php (34)
in C:\xampp\htdocs\hs\index.php (13)
2014/09/18 00:55:39 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\hs\protected\controllers\SiteController.php:34)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\hs\index.php(13): CWebApplication->run()
REQUEST_URI=/hs/
in C:\xampp\htdocs\hs\protected\controllers\SiteController.php (34)
in C:\xampp\htdocs\hs\index.php (13)
2014/10/16 01:23:45 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'active' in 'where clause'. The SQL statement executed was: SELECT * FROM `user` `t` WHERE login = :userEmail AND active = 1 LIMIT 1.
in C:\xampp\htdocs\hs\protected\models\User.php (169)
in C:\xampp\htdocs\hs\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\hs\protected\models\LoginForm.php (52)
2014/10/16 01:23:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'active' in 'where clause'. The SQL statement executed was: SELECT * FROM `user` `t` WHERE login = :userEmail AND active = 1 LIMIT 1' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1351): CDbCommand->queryRow()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1456): CActiveRecord->query(Object(CDbCriteria))
#3 C:\xampp\htdocs\hs\protected\models\User.php(169): CActiveRecord->find(Array)
#4 C:\xampp\htdocs\hs\protected\components\UserIdentity.php(25): User::findByEmail('denisthadeu@hot...')
#5 C:\xampp\htdocs\hs\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#6 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#7 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#8 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#9 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(44): CModel->validate()
#10 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#16 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/hs/
HTTP_REFERER=http://localhost/hs/
---
2014/10/16 01:27:20 [error] [php] include(PasswordHash.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\hs\protected\models\User.php(152): spl_autoload_call()
#1 C:\xampp\htdocs\hs\protected\components\UserIdentity.php(34): User->matchPassword()
#2 C:\xampp\htdocs\hs\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#6 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(44): LoginForm->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\hs\index.php(13): CWebApplication->run()
REQUEST_URI=/hs/
in C:\xampp\htdocs\hs\protected\models\User.php (152)
in C:\xampp\htdocs\hs\protected\components\UserIdentity.php (34)
in C:\xampp\htdocs\hs\protected\models\LoginForm.php (52)
2014/10/16 01:32:24 [error] [exception.CException] exception 'CException' with message 'LoginForm and its behaviors do not have a method or closure named "save".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(44): CComponent->__call('save', Array)
#1 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(44): LoginForm->save()
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/hs/
HTTP_REFERER=http://localhost/hs/
---
2014/10/16 01:35:13 [error] [exception.CException] exception 'CException' with message 'LoginForm and its behaviors do not have a method or closure named "save".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(44): CComponent->__call('save', Array)
#1 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(44): LoginForm->save()
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/hs/
HTTP_REFERER=http://localhost/hs/
---
2014/10/16 01:41:03 [error] [exception.CException] exception 'CException' with message 'LoginForm and its behaviors do not have a method or closure named "save".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(44): CComponent->__call('save', Array)
#1 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(44): LoginForm->save()
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/hs/
HTTP_REFERER=http://localhost/hs/
---
2014/10/16 01:41:22 [error] [exception.CException] exception 'CException' with message 'Property "User.rememberMe" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('rememberMe')
#1 C:\xampp\htdocs\yii\framework\validators\CBooleanValidator.php(56): CActiveRecord->__get('rememberMe')
#2 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CBooleanValidator->validateAttribute(Object(User), 'rememberMe')
#3 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(User), NULL)
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(805): CModel->validate(NULL)
#5 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(47): CActiveRecord->save()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/hs/
HTTP_REFERER=http://localhost/hs/
---
2014/10/16 01:42:23 [error] [exception.CException] exception 'CException' with message 'Property "User.username" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('username')
#1 C:\xampp\htdocs\hs\protected\models\User.php(110): CActiveRecord->__get('username')
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): User->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(User), 'password')
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(User), NULL)
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(805): CModel->validate(NULL)
#6 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(47): CActiveRecord->save()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/hs/
HTTP_REFERER=http://localhost/hs/
---
2014/10/16 02:15:09 [error] [exception.CException] exception 'CException' with message 'Property "User.username" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('username')
#1 C:\xampp\htdocs\hs\protected\models\User.php(110): CActiveRecord->__get('username')
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): User->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(User), 'password')
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(User), NULL)
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(805): CModel->validate(NULL)
#6 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(47): CActiveRecord->save()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/hs/index.php
HTTP_REFERER=http://localhost/hs/index.php
---
2014/10/16 02:17:40 [error] [exception.CException] exception 'CException' with message 'Property "User.username" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('username')
#1 C:\xampp\htdocs\hs\protected\models\User.php(110): CActiveRecord->__get('username')
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): User->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(User), 'password')
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(User), NULL)
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(805): CModel->validate(NULL)
#6 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(47): CActiveRecord->save()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/hs/index.php
HTTP_REFERER=http://localhost/hs/index.php
---
2014/10/16 02:19:05 [error] [exception.CException] exception 'CException' with message 'Property "User.name" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('name')
#1 C:\xampp\htdocs\hs\protected\models\User.php(110): CActiveRecord->__get('name')
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): User->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(User), 'password')
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(User), NULL)
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(805): CModel->validate(NULL)
#6 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(47): CActiveRecord->save()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/hs/index.php
HTTP_REFERER=http://localhost/hs/index.php
---
2014/10/16 02:19:17 [error] [exception.CException] exception 'CException' with message 'Property "User.name" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('name')
#1 C:\xampp\htdocs\hs\protected\models\User.php(110): CActiveRecord->__get('name')
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): User->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(User), 'password')
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(User), NULL)
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(805): CModel->validate(NULL)
#6 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(47): CActiveRecord->save()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/hs/index.php
HTTP_REFERER=http://localhost/hs/index.php
---
2014/10/16 02:19:48 [error] [exception.CException] exception 'CException' with message 'Property "User._identity" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(161): CComponent->__set('_identity', Object(UserIdentity))
#1 C:\xampp\htdocs\hs\protected\models\User.php(110): CActiveRecord->__set('_identity', Object(UserIdentity))
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): User->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(User), 'password')
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(User), NULL)
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(805): CModel->validate(NULL)
#6 C:\xampp\htdocs\hs\protected\controllers\SiteController.php(47): CActiveRecord->save()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\hs\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/hs/index.php
HTTP_REFERER=http://localhost/hs/index.php
---
